/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Clip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'animeName' : IDL.Text,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
  'uploadDate' : Time,
});
export const ClipRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'animeName' : IDL.Text,
  'requesterContact' : IDL.Text,
  'requestDate' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addClip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Clip],
      [],
    ),
  'deleteClip' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteClipRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllClipRequests' : IDL.Func([], [IDL.Vec(ClipRequest)], ['query']),
  'getAllClips' : IDL.Func([], [IDL.Vec(Clip)], ['query']),
  'getClipsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Clip)], ['query']),
  'searchClips' : IDL.Func([IDL.Text], [IDL.Vec(Clip)], ['query']),
  'submitClipRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ClipRequest],
      [],
    ),
  'updateRequestStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(ClipRequest)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Clip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'animeName' : IDL.Text,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
    'uploadDate' : Time,
  });
  const ClipRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'animeName' : IDL.Text,
    'requesterContact' : IDL.Text,
    'requestDate' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addClip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Clip],
        [],
      ),
    'deleteClip' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteClipRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllClipRequests' : IDL.Func([], [IDL.Vec(ClipRequest)], ['query']),
    'getAllClips' : IDL.Func([], [IDL.Vec(Clip)], ['query']),
    'getClipsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Clip)], ['query']),
    'searchClips' : IDL.Func([IDL.Text], [IDL.Vec(Clip)], ['query']),
    'submitClipRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ClipRequest],
        [],
      ),
    'updateRequestStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(ClipRequest)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };